Repository tihlde/Kvark, pull requests merged in 2021-01, with the labels that each got.

#343 refactor(typescript): login and companies
  .eslintrc.json
  src/URLS.tsx
  src/api/fetch.tsx
  src/api/hooks/Auth.tsx
  src/components/inputs/TextField.tsx
  src/components/layout/Container.tsx
  src/components/layout/InfoCard.tsx
  src/components/miscellaneous/MessageGDPR.tsx
  src/components/navigation/Navigation.tsx
  src/constant.tsx
  src/containers/Companies/components/CompaniesForm.tsx
  src/containers/Companies/components/Forum.js
  src/containers/Companies/index.js
  src/containers/Companies/index.tsx
  src/containers/Landing/index.tsx
  src/containers/LogIn/index.js
  src/containers/LogIn/index.tsx
  src/setupTests.tsx
  src/text/CompaniesText.js
  src/text/LogInText.js
  src/theme.tsx
Labels: refactor

#311 refactor(profile): refactor profile to typescript
  src/components/inputs/Dropdown.tsx
  src/containers/Profile/components/ProfileBadges.tsx
  src/containers/Profile/components/ProfileEvents.js
  src/containers/Profile/components/ProfileEvents.tsx
  src/containers/Profile/components/ProfileNotifications.js
  src/containers/Profile/components/ProfileNotifications.tsx
  src/containers/Profile/components/ProfilePaper.tsx
  src/containers/Profile/components/ProfileSettings.tsx
  src/containers/Profile/index.tsx
  src/types/Types.tsx
Labels: refactor

#348 refactor(navigation): split up files and new sidebar design
  src/components/navigation/Navigation.tsx
  src/components/navigation/Sidebar.tsx
  src/components/navigation/Topbar.tsx
Labels: enhancement, refactor

#355 feat(stories): collect events, news and jobposts in one at landing page
  src/components/story/Story.tsx
  src/containers/Events/index.js
  src/containers/Landing/components/EventsListView.tsx
  src/containers/Landing/components/EventsView.tsx
  src/containers/Landing/components/NewsListView.tsx
  src/containers/Landing/components/StoriesView.tsx
  src/containers/Landing/index.tsx
  src/types/Types.tsx
Labels: enhancement
