Repository tihlde/Kvark, pull requests merged in 2021-02, with the labels that each got.

#357 feat(markdown): custom markdown components
  CHANGELOG.md
  src/api/hooks/Event.tsx
  src/api/hooks/JobPost.tsx
  src/api/hooks/News.tsx
  src/components/inputs/MarkdownEditor.tsx
  src/components/layout/Expand.tsx
  src/components/miscellaneous/MarkdownRenderer.tsx
Labels: enhancement

#354 fix(forms): create submitbutton which displays errors
  CHANGELOG.md
  src/components/inputs/SubmitButton.tsx
  src/containers/Companies/components/CompaniesForm.tsx
  src/containers/EventAdministration/components/EventEditor.tsx
  src/containers/ForgotPassword/index.tsx
  src/containers/LogIn/index.tsx
  src/containers/SignUp/index.tsx
Labels: bug, enhancement, refactor

#356 feat(loading): add skeleton versions for loading listitem and story
  CHANGELOG.md
  src/components/miscellaneous/ListItem.tsx
  src/components/navigation/Topbar.tsx
  src/components/story/Story.tsx
  src/components/story/StoryPopup.tsx
  src/containers/Cheatsheet/index.tsx
  src/containers/Events/index.js
  src/containers/Landing/components/EventsListView.tsx
  src/containers/Landing/components/NewsListView.tsx
  src/containers/Landing/components/StoriesView.tsx
  src/containers/Landing/index.tsx
  src/containers/News/index.js
  src/containers/Profile/components/ProfileEvents.tsx
  src/containers/Profile/components/ProfilePaper.tsx
Labels: enhancement, refactor

#347 feat(pages): create pages and pagesadmin
  CHANGELOG.md
  package.json
  src/URLS.tsx
  src/api/api.tsx
  src/api/hooks/Pages.tsx
  src/components/layout/Banner.tsx
  src/components/layout/Dialog.tsx
  src/components/layout/Tabs.tsx
  src/containers/About/index.js
  src/containers/Companies/index.tsx
  src/containers/EventDetails/components/EventRenderer.tsx
  src/containers/Pages/components/PagesAdmin.tsx
  src/containers/Pages/components/PagesList.tsx
  src/containers/Pages/index.tsx
  src/index.tsx
  src/types/Types.tsx
  src/utils.tsx
  yarn.lock
Labels: enhancement

#365 refactor(jobpost): to typescript and react query
  src/api/api.tsx
  src/api/hooks/JobPost.tsx
  src/components/inputs/TextField.tsx
  src/components/layout/Pageination.tsx
  src/components/layout/SidebarList.tsx
  src/components/miscellaneous/DetailContent.tsx
  src/components/miscellaneous/MarkdownRenderer.tsx
  src/components/miscellaneous/RendererPreview.tsx
  src/containers/Cheatsheet/components/Files.tsx
  src/containers/EventAdministration/components/EventEditor.tsx
  src/containers/EventAdministration/index.tsx
  src/containers/EventDetails/components/EventRenderer.tsx
  src/containers/EventDetails/index.tsx
  src/containers/Events/index.js
  src/containers/JobPostAdministration/components/JobPostEditor.js
  src/containers/JobPostAdministration/components/JobPostEditor.tsx
  src/containers/JobPostAdministration/index.js
  src/containers/JobPostAdministration/index.tsx
  src/containers/JobPostDetails/components/JobPostRenderer.js
  src/containers/JobPostDetails/components/JobPostRenderer.tsx
  src/containers/JobPostDetails/index.js
  src/containers/JobPostDetails/index.tsx
  src/containers/JobPosts/components/NoPostsIndicator.js
  src/containers/JobPosts/index.js
  src/containers/JobPosts/index.tsx
  src/containers/Landing/components/StoriesView.tsx
  src/containers/Landing/index.tsx
  src/containers/UserAdmin/tabs/Members.js
  src/index.tsx
  src/text/JobPostText.js
  src/types/Types.tsx
Labels: enhancement, refactor

#366 fix(pages): error handling and cache improvements
  CHANGELOG.md
  src/api/hooks/Pages.tsx
  src/api/hooks/Snackbar.tsx
  src/components/inputs/MarkdownEditor.tsx
  src/components/miscellaneous/MarkdownRenderer.tsx
  src/components/miscellaneous/MessageGDPR.tsx
  src/containers/EventDetails/components/EventRenderer.tsx
  src/containers/Landing/components/StoriesView.tsx
  src/containers/Pages/components/PagesAdmin.tsx
  src/containers/Pages/index.tsx
  src/containers/SignUp/index.tsx
Labels: bug, refactor

#364 refactor(event): create a EventCompact type for list of events
  src/api/api.tsx
  src/components/miscellaneous/ListItem.tsx
  src/components/story/Story.tsx
  src/containers/EventAdministration/components/EventEditor.tsx
  src/containers/EventAdministration/index.tsx
  src/containers/Landing/components/EventsCalendarView.tsx
  src/containers/Landing/components/EventsListView.tsx
  src/containers/Landing/components/EventsView.tsx
  src/containers/Landing/components/StoriesView.tsx
  src/containers/Landing/index.tsx
  src/containers/Profile/components/ProfileEvents.tsx
  src/types/Types.tsx
Labels: refactor

#374 refactor(user): user to react query and useradmin to typescript
  src/api/api.tsx
  src/api/hooks/Auth.tsx
  src/api/hooks/Event.tsx
  src/api/hooks/User.tsx
  src/components/navigation/Sidebar.tsx
  src/components/navigation/Topbar.tsx
  src/containers/Cheatsheet/index.tsx
  src/containers/EventDetails/components/EventRenderer.tsx
  src/containers/ForgotPassword/index.tsx
  src/containers/Http404/index.js
  src/containers/Landing/components/Wave.tsx
  src/containers/LogIn/index.tsx
  src/containers/Profile/components/ProfileAdmin.tsx
  src/containers/Profile/components/ProfileBadges.tsx
  src/containers/Profile/components/ProfileEvents.tsx
  src/containers/Profile/components/ProfilePaper.tsx
  src/containers/Profile/components/ProfileSettings.tsx
  src/containers/Profile/index.tsx
  src/containers/SignUp/index.tsx
  src/containers/UserAdmin/components/PersonListItem.tsx
  src/containers/UserAdmin/index.js
  src/containers/UserAdmin/index.tsx
  src/containers/UserAdmin/tabs/Members.js
  src/containers/UserAdmin/tabs/components/PersonListItem.js
  src/index.tsx
Labels: enhancement, refactor

#375 refactor(news): changed all files related to news to typescript
  src/api/api.tsx
  src/api/hooks/News.tsx
  src/components/layout/SidebarList.tsx
  src/components/miscellaneous/MarkdownRenderer.tsx
  src/containers/Landing/components/NewsListView.tsx
  src/containers/Landing/components/StoriesView.tsx
  src/containers/Landing/index.tsx
  src/containers/News/index.js
  src/containers/News/index.tsx
  src/containers/NewsAdministration/components/NewsEditor.js
  src/containers/NewsAdministration/components/NewsEditor.tsx
  src/containers/NewsAdministration/index.js
  src/containers/NewsAdministration/index.tsx
  src/containers/NewsDetails/components/NewsRenderer.js
  src/containers/NewsDetails/components/NewsRenderer.tsx
  src/containers/NewsDetails/index.js
  src/containers/NewsDetails/index.tsx
  src/index.tsx
  src/types/Types.tsx
Labels: refactor

#384 refactor(new-footer): redesign the footer
  src/components/navigation/Footer.tsx
Labels: refactor

#381 refactor(sidebarlist): simplify sidebarlist and make icons rounded
  CHANGELOG.md
  src/api/hooks/News.tsx
  src/components/inputs/MarkdownEditor.tsx
  src/components/layout/Expand.tsx
  src/components/layout/Pagination.tsx
  src/components/layout/SidebarList.tsx
  src/components/miscellaneous/ListItem.tsx
  src/components/miscellaneous/RendererPreview.tsx
  src/components/navigation/Footer.tsx
  src/components/navigation/Snack.tsx
  src/components/navigation/Topbar.tsx
  src/containers/Cheatsheet/components/Files.tsx
  src/containers/EventAdministration/components/EventEditor.tsx
  src/containers/EventAdministration/components/Participant.tsx
  src/containers/EventAdministration/index.tsx
  src/containers/Events/index.tsx
  src/containers/JobPostAdministration/index.tsx
  src/containers/JobPosts/index.tsx
  src/containers/Landing/components/EventsView.tsx
  src/containers/News/index.tsx
  src/containers/NewsAdministration/index.tsx
  src/containers/NewsDetails/components/NewsRenderer.tsx
  src/containers/Pages/components/PagesAdmin.tsx
  src/containers/Profile/components/ProfileNotifications.tsx
  src/containers/Profile/components/ProfilePaper.tsx
  src/containers/UserAdmin/index.tsx
Labels: refactor

#380 refactor(useradmin): update listview
  src/containers/EventDetails/components/EventRenderer.tsx
  src/containers/JobPostDetails/components/JobPostRenderer.tsx
  src/containers/Profile/index.tsx
  src/containers/UserAdmin/components/PersonListItem.tsx
Labels: refactor

#387 refactor(events): allow unregister after deadline if on wait
  CHANGELOG.md
  src/containers/EventDetails/components/EventRenderer.tsx
Labels: enhancement

#393 refactor(pages): move content to pages
  .github/pull_request_template.md
  CHANGELOG.md
  src/URLS.tsx
  src/components/miscellaneous/BadgeInput.tsx
  src/components/navigation/Navigation.tsx
  src/components/navigation/Topbar.tsx
  src/containers/About/index.js
  src/containers/ContactInfo/index.js
  src/containers/EventRules/index.js
  src/containers/Http404/index.js
  src/containers/Http404/index.tsx
  src/containers/JobPostDetails/index.tsx
  src/containers/Laws/index.tsx
  src/containers/NewStudent/index.js
  src/containers/Pages/index.tsx
  src/containers/PrivacyPolicy/index.js
  src/containers/Profile/components/ProfileAdmin.tsx
  src/containers/Services/index.js
  src/index.tsx
  src/text/AboutText.js
  src/text/AdminText.js
  src/text/ContactText.js
  src/text/EventText.js
  src/text/NewStudentText.js
  src/text/ServicesText.js
  tsconfig.json
Labels: enhancement, refactor
